# -*- coding: utf-8 -*-
# Copyright (c) 2026 Suzhou Jodell Robotics Co., Ltd.
# Author: Gui LI <guilichina@163.com>
# Date:   2026-05-25
# UPDATE: 2026-05-28 — add OrnsteinUhlenbeckNoise per Theory §14.2
#
# This file is part of the UID Theory reference implementation.
#
# DUAL LICENSE:
#   - PolyForm Noncommercial License 1.0.0  (academic / personal use)
#     see LICENSE-NONCOMMERCIAL in the project root
#   - Commercial License from Suzhou Jodell Robotics Co., Ltd.
#     (required for any commercial / for-profit / production use)
#     see LICENSE-COMMERCIAL in the project root
#
# For commercial licensing inquiries, contact: lig@jodell.cn
# 本文件采用双许可证发布；商业使用须先获得苏州钧舵机器人有限公司书面授权，
# 商业授权联系: lig@jodell.cn

"""Colored-noise generators for CID.

色噪声生成器 —— 提供两个实现：

1. ``OrnsteinUhlenbeckNoise`` (RECOMMENDED, §14.2 default):
       Physically correct OU process generated by a local SDE.
       Steady-state correlation:  <xi(t) xi(t+s)> = exp(-|s|/tau).
       Couples self-consistently to the sub-Ohmic memory kernel via
       the fluctuation-dissipation theorem.
       Only +1 learnable scalar per layer (log_sigma).

2. ``FastColoredNoise`` (LEGACY, fast 1/f^beta shaping):
       Direct FFT shaping of white noise to 1/f^beta spectrum.
       Useful for quick spectrum checks, BUT carries a HIGH RISK of
       circular measurement: if injected at train time, any post-hoc
       spectral measurement may just echo the injected spectrum
       instead of reflecting CID's intrinsic emergent dynamics.
       Use only with explicit ``set_noise_injection(False)`` at
       measurement time.

理论依据：神经雪崩、皮层 EEG 与 MEG 普遍呈现 1/f^beta 谱
（He, 2014; Linkenkaer-Hansen et al., 2001）。CID 主方程将色阻尼 +
色涨落作为内嵌机制，使系统具备长程时间依赖。

OU 噪声是物理上自洽的色噪声实现，与亚欧姆记忆核共同满足涨落-耗散关系；
FFT 整形噪声仅作为快速对比工具。
"""

from __future__ import annotations

import math
from typing import Optional

import torch
import torch.nn as nn


# ======================================================================
# RECOMMENDED: Ornstein-Uhlenbeck colored noise (§14.2)
# ======================================================================


class OrnsteinUhlenbeckNoise(nn.Module):
    """Ornstein-Uhlenbeck colored noise per Theory §14.2.

    OU 色噪声 —— 由局部 SDE 生成，物理上自洽，符合 §14.2 的默认推荐。

    Underlying SDE:
        d xi  =  -xi / tau * dt  +  sqrt(2 / tau) * dW

    Steady-state properties:
        Variance        : Var[xi] = 1
        Auto-correlation: <xi(t) xi(t+s)> = exp(-|s| / tau)
        Power spectrum  : S(omega) = 2 tau / (1 + (omega tau)^2)

    Compared with FFT-shaped 1/f noise, OU noise:
      * is generated by a LOCAL update (no global FFT), matching the
        physical picture of multi-bath coupling;
      * has a finite correlation time tau, not an unphysical
        instantaneous global correlation;
      * couples self-consistently to the sub-Ohmic memory kernel via
        the fluctuation-dissipation theorem;
      * avoids the "circular measurement" problem when one later
        wants to measure intrinsic 1/f exponents.

    Parameters per layer: exactly 1 learnable scalar (``log_sigma``),
    in compliance with §14.2.
    """

    def __init__(
        self,
        dim: int = 768,
        tau: float = 10.0,
        learnable_sigma: bool = True,
    ) -> None:
        """Initialise the OU noise generator.

        Args:
            dim:             Feature dimension D. 特征维度。
            tau:             Correlation time (in token / step units).
                             相关时间（以 token / 步为单位）。
            learnable_sigma: If True, the amplitude scalar ``sigma`` is
                             learnable; otherwise it is fixed.
                             是否将幅度 sigma 设为可学习。
        """
        super().__init__()
        if dim <= 0:
            raise ValueError(f"dim must be positive, got {dim}")
        if tau <= 0.0:
            raise ValueError(f"tau must be positive, got {tau}")
        self.dim: int = int(dim)
        self.tau: float = float(tau)
        # Expose ``beta`` for backwards compatibility with diagnostic
        # tooling that reads it; OU does not have a single spectral
        # slope so we report None.
        self.beta: Optional[float] = None

        # log-parameterise so sigma > 0 always.
        # 用 log 参数化以保证 sigma > 0。
        if learnable_sigma:
            self.log_sigma: nn.Parameter = nn.Parameter(torch.tensor(-3.0))
            self.register_buffer("_fixed_log_sigma", None)
        else:
            self.log_sigma = None  # type: ignore[assignment]
            self.register_buffer(
                "_fixed_log_sigma", torch.tensor(-3.0)
            )

    def _sigma(self) -> torch.Tensor:
        if self.log_sigma is not None:
            return torch.exp(self.log_sigma)
        return torch.exp(self._fixed_log_sigma)  # type: ignore[arg-type]

    def forward(
        self,
        batch_size: int,
        seq_len: int,
        device: torch.device,
        dtype: torch.dtype = torch.float32,
    ) -> torch.Tensor:
        """Sample OU colored noise of shape (B, S, D).

        We use the EXACT discrete OU update (not Euler), correct at any
        step size:
            decay      = exp(-1 / tau)
            kick_scale = sqrt(1 - decay^2)
            xi[t+1]    = decay * xi[t]  +  kick_scale * N(0, 1)

        which gives steady-state variance Var[xi] = 1.
        Final output is then scaled by the learnable amplitude sigma.

        Args:
            batch_size: Batch size B. 批大小。
            seq_len:    Sequence length S (>= 1). 序列长度。
            device:     Target device. 目标设备。
            dtype:      Target dtype. 目标数据类型。

        Returns:
            Tensor of shape (B, S, D) with steady-state Var = sigma^2.
        """
        if seq_len < 1:
            raise ValueError(f"seq_len must be >= 1, got {seq_len}")

        decay = math.exp(-1.0 / self.tau)
        kick_scale = math.sqrt(max(1.0 - decay * decay, 0.0))

        # Initialise hidden OU state at its steady-state distribution
        # N(0, 1). We re-init every forward to keep the autograd graph
        # clean and to avoid state leakage between batches.
        # 每次前向重新初始化 OU 隐状态到稳态分布 N(0, 1)。
        state = torch.randn(
            batch_size, self.dim, device=device, dtype=dtype
        )

        # Sequential generation along the time axis.
        # Time cost is O(S * D), same order as the memory-kernel conv.
        # 沿时间轴顺序生成；总开销 O(S * D)，与记忆核卷积同阶。
        out = torch.empty(
            batch_size, seq_len, self.dim, device=device, dtype=dtype
        )
        for t in range(seq_len):
            kick = torch.randn(
                batch_size, self.dim, device=device, dtype=dtype
            )
            state = decay * state + kick_scale * kick
            out[:, t, :] = state

        sigma = self._sigma()
        return sigma * out


# ======================================================================
# LEGACY: FFT-shaped colored noise (kept for backward compatibility)
# ======================================================================


class FastColoredNoise(nn.Module):
    """Vectorised FFT-based 1/f^beta colored-noise generator.

    使用 FFT 在批维度与隐维度上向量化的色噪声生成器；
    单次调用即可生成 (B, S, D) 形状的色噪声样本。

    .. warning::
       This generator carries a HIGH RISK of *circular measurement*:
       any spectrum measured on hidden states after this noise has been
       injected will simply echo the injected spectrum, NOT the
       intrinsic emergent CID dynamics.

       For honest measurement of emergent critical exponents (1/f,
       Hurst, avalanches), prefer ``OrnsteinUhlenbeckNoise`` and / or
       explicitly disable injection at measurement time via
       ``CIDLayer.set_noise_injection(False)``.

    Attributes:
        beta: Spectral slope, S(omega) ~ omega^(-beta).
              0 -> white; 1 -> pink (1/f); 2 -> red (Brownian).
        dim:  Per-token feature dimension.
    """

    def __init__(self, beta: float = 1.0, dim: int = 768) -> None:
        """Initialise the FFT colored-noise generator.

        Args:
            beta: Target spectral slope (default 1.0 -> pink noise).
            dim:  Feature dimension over which independent noise channels
                  are drawn.
        """
        super().__init__()
        if dim <= 0:
            raise ValueError(f"dim must be positive, got {dim}")
        self.beta: float = float(beta)
        self.dim: int = int(dim)

    def forward(
        self,
        batch_size: int,
        seq_len: int,
        device: torch.device,
        dtype: torch.dtype = torch.float32,
    ) -> torch.Tensor:
        """Sample a colored-noise tensor of shape (B, S, D).

        Args:
            batch_size: Batch size B. 批大小。
            seq_len:    Sequence length S (>= 4). 序列长度。
            device:     Target device. 目标设备。
            dtype:      Target dtype. 目标数据类型。

        Returns:
            Tensor of shape (batch_size, seq_len, self.dim), unit
            variance along the sequence axis.
            形状 (B, S, D) 的色噪声张量，沿序列维归一化为单位方差。
        """
        if seq_len < 4:
            raise ValueError(f"seq_len must be >= 4, got {seq_len}")

        # rfft frequency grid (length seq_len // 2 + 1).
        # 实数 FFT 的频率轴。
        freqs = torch.fft.rfftfreq(seq_len, device=device, dtype=dtype)
        # Replace the zero-frequency bin with a small positive number
        # to avoid division by zero in the power-law factor.
        # 用一个小正数替代 0 频，避免除零。
        freqs = torch.where(
            freqs == 0,
            torch.full_like(freqs, 1.0e-10),
            freqs,
        )
        amp = freqs.pow(-self.beta / 2.0)  # shape: (n_freq,)

        # White noise on all (B, S, D) entries.
        white = torch.randn(
            batch_size, seq_len, self.dim, device=device, dtype=dtype
        )
        fft_white = torch.fft.rfft(white, dim=1)
        # Broadcast amp over (B, n_freq, D).
        fft_colored = fft_white * amp[None, :, None]
        out = torch.fft.irfft(fft_colored, n=seq_len, dim=1)

        # Normalise so that per-channel std along the time axis is ~1.
        # 沿时间维标准化到单位方差。
        std = out.std(dim=1, keepdim=True)
        return out / (std + 1.0e-8)
